[dev-dependencies]
bench = "2.0.1"
base = "0.16.0"

[dependencies]
base = "0.16.0"
core = "2.4.0"
stableheapbtreemap = "1.5.0"
star = "0.1.1"
map = "9.0.1"
vector = "0.4.6"
candy = "0.3.1"
class-plus = "0.2.1"
timer-tool = "0.2.1"
champ-map = "0.1.0"

[package]
name = "icrc72-publisher-mo"
version = "0.0.2"
description = "manage publications for icrc72"
repository = "https://github.com/icdevsorg/icrc72-publisher-mo"
keywords = [ "pubsub" ]

[toolchain]
moc = "1.8.2"
